### PR TITLE
Treat oauth config as a secret

### PR DESCRIPTION
**Pull request by antrix**
Oauth config values generally have sensitive data that we don't want to commit to git. 

This PR introduces two changes:
* Converts `oauth.json` from a configmap to a Secret.
* Allows referencing an externally provisioned Secret instead of the helm generated secret.

### CODE REVIEW

**Comment by rubenfiszel** [comment]
That makes a lot of sense and thank you for the contribution.

I think i'd rather remove enableOAuth and have it always enabled, it will just refer to an empty oauth.json in the worst case.

`if .Values.windmill.oauthSecretName` will return false if oauthSecretName == "" ?

**Comment by antrix** [comment]
> if .Values.windmill.oauthSecretName will return false if oauthSecretName == "" ?

It should. My local template generation worked according to this logic.

Also, from [the Helm docs](https://helm.sh/docs/chart_template_guide/control_structures/):
> A pipeline is evaluated as false if the value is:
> * a boolean false
> * a numeric zero
> * an empty string

**Comment by antrix** [comment]
> I think i'd rather remove enableOAuth and have it always enabled
I can update the PR with this. Shall I?

**Comment by rubenfiszel** [comment]
Yes please, can you update that part and bump the version to make the linter happy :)

Thanks a lot!

**Comment by antrix** [comment]
Pushed new commits. But not sure how to get the linter tests to run again.

**Pull request merged**
