### PR TITLE
Use `{{ .Release.Name }}` in Kubernetes resource names

### PR DESCRIPTION
**Pull request by NiklasRosenstein**

### CODE REVIEW

**Comment by rubenfiszel** [comment]
Thanks for the PR! I wasn't aware of this good practice but makes sense!

**Comment by NiklasRosenstein** [comment]
Thanks for merging @rubenfiszel !

I just realized that this isn't working well with the hardcoded default `windmill.databaseUrl` in `values.yaml` because the hostname would need to be `{{ .Release.Name }}-postgres`. The variable won't be recognized in `values.yaml` unless it is explicitly evaluated later where the value is used (example here: https://stackoverflow.com/a/62896363/791713).

**Comment by NiklasRosenstein** [comment]
Would you prefer we evaluate the URL as a template or have it default to "null" and treat that as a special case to automatically construct the database URL?

**Comment by rubenfiszel** [comment]
The simplest would probably to keep postgres to being static since it's not very release dependent

**Comment by rubenfiszel** [comment]
I reverted postgres meta name, but I wonder if it will not be the same issue wrt to baseInternalUrl relying on the static dns name

**Comment by rubenfiszel** [comment]
Yeah I have to revert everything for now unfortunately

**Pull request merged**
